
# POST http://localhost:3033/auth/login
POST https://traaning.herokuapp.com/auth/login
Content-Type: application/json

{
    "brugernavn": "julie",
    "password": "seme"
}

###
# GET http://localhost:3033/auth/logout
GET https://traaning.herokuapp.com/auth/logout

###
# GET http://localhost:3033/auth/loggedin
GET https://traaning.herokuapp.com/auth/loggedin