# GET http://localhost:3033/admin/bruger/tester
GET https://traaning.herokuapp.com/admin/bruger/tester

###


# GET http://localhost:3033/admin/bruger
GET https://traaning.herokuapp.com/admin/bruger

###

# GET http://localhost:3033/admin/bruger/5ee9feffa23bdf03bc950a9b
GET https://traaning.herokuapp.com/admin/bruger/5eeb17567242a100170180a8
###
# POST http://localhost:3033/admin/bruger
POST https://traaning.herokuapp.com/admin/bruger
Content-Type: application/json

{
    "brugernavn": "julie",
    "navn": "julie",
    "email": "julie@gmail.com",
    "password": "seme"
}

###
# DELETE http://localhost:3033/admin/bruger/5ee9feffa23bdf03bc950a9b
DELETE https://traaning.herokuapp.com/admin/bruger/5eeb17567242a100170180a8
###
# PATCH http://localhost:3033/admin/bruger/5ee9feffa23bdf03bc950a9b
PATCH https://traaning.herokuapp.com/admin/bruger/5eeb17567242a100170180a8
Content-Type: application/json

{
    "brugernavn": "Kimmie"
}

