# GET http://localhost:3033/admin/bruger/tester
GET https://traaning.herokuapp.com/admin/bruger/tester

###


# GET http://localhost:3033/admin/bruger
GET https://traaning.herokuapp.com/admin/bruger

###

# GET http://localhost:3033/admin/bruger/5ee9feffa23bdf03bc950a9b
GET https://traaning.herokuapp.com/admin/bruger/5eea04ce876a8c09980e6e6f
###
# POST http://localhost:3033/admin/bruger
POST https://traaning.herokuapp.com/admin/bruger
Content-Type: application/json

{
    "brugernavn": "emma",
    "navn": "emma",
    "email": "emma@gmail.com",
    "password": "seme"
}

###
# DELETE http://localhost:3033/admin/bruger/5ee9feffa23bdf03bc950a9b
DELETE https://traaning.herokuapp.com/admin/bruger/5eea04ce876a8c09980e6e6f
###
# PATCH http://localhost:3033/admin/bruger/5ee9feffa23bdf03bc950a9b
PATCH https://traaning.herokuapp.com/admin/bruger/5eea04ce876a8c09980e6e6f
Content-Type: application/json

{
    "brugernavn": "Kimmie"
}

