# GET http://localhost:3033/oevelser/tester
GET https://traaning.herokuapp.com/oevelser/tester
###


# GET http://localhost:3033/oevelser
GET https://traaning.herokuapp.com/oevelser

###

# GET http://localhost:3033/oevelser/admin/dine-oevelser
GET https://traaning.herokuapp.com/oevelser/admin/dine-oevelser

###

# GET http://localhost:3033/oevelser/5ee9ff89cf78291ce0b12cdb
GET https://traaning.herokuapp.com/oevelser/5eeb2a5c494b1d0017b24c33

###
# POST http://localhost:3033/oevelser/admin
POST https://traaning.herokuapp.com/oevelser/admin
Content-Type: application/json

{
    "oevelseNavn": "surt",
    "oevelseBeskrivelse": "citroner og mere"
}

###
# DELETE http://localhost:3033/oevelser/admin/5ee9ff89cf78291ce0b12cdb
DELETE https://traaning.herokuapp.com/oevelser/admin/5eeb1b88f3eeb500175e268a

###
# PATCH http://localhost:3033/oevelser/admin/5ee9ff89cf78291ce0b12cdb
PATCH https://traaning.herokuapp.com/oevelser/admin/5eeb1b88f3eeb500175e268a
Content-Type: application/json

{
    "oevelseNavn": "New overskrift"
}
